/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b4c5ff",
        "on-secondary-container": "#6f5900",
        "on-tertiary-container": "#ffecea",
        "surface-dim": "#d2d9f4",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#231b00",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        tertiary: "#ab0b1c",
        "primary-fixed": "#dbe1ff",
        outline: "#737686",
        "on-primary": "#ffffff",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        background: "#faf8ff",
        error: "#ba1a1a",
        "on-surface-variant": "#434655",
        "secondary-container": "#fed01b",
        primary: "#004ac6",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed-dim": "#eec200",
        "surface-variant": "#dae2fd",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#cf2c30",
        "on-tertiary-fixed": "#410004",
        "on-secondary-fixed-variant": "#574500",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdad7",
        "inverse-surface": "#283044",
        "surface-tint": "#0053db",
        secondary: "#735c00",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed": "#ffe083",
        surface: "#faf8ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "section-padding": "80px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
